### ISSUE TITLE
ltms.app

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#1422]
### Comments

> We build tooling for email marketers, so it is common for our domains to be copy and pasted into Phishing emails
> source: @brianfeucht

### Wildcard domain records

```CSV
ltms.app|adware,tracking
```

### Sub-Domain records

```CSV
null
```

### Hosts (RFC:953) specific records, not used by DNS RPZ firewalls

```CSV
click.ltms.app|adware,tracking
```

### SeafeSearch records

```CSV
null
```

### Screenshots

N/A

### Links to external sources

```CSS
https://github.com/Phishing-Database/phishing/pull/535
```

### logs from uBlock Origin

N/A

**Comment by brianfeucht** [comment]
@spirillen this domain is used for content automation in emails.  We do not provide tracking/clicking data to our customers.  So tagging this domain as AdWare or Tracking is not accurate.

For a specific example, this domain is used for helping build "Add To Calendar" buttons for appointments or events.  A use case might be if you purchased a ticket to a concert, you could generate an appropriate ICS file to allow someone to add the event details to their personal calendar (turns out this isn't an easy problem!)

**Comment by spirillen** [comment]
Hi @brianfeucht thanks for your feedback, but your comment

> We build tooling for email marketers,

Makes this rather difficult to see. In my universe `email marketers` are adware with tracking...

I'll fix this in a minut, also https://github.com/Phishing-Database/phishing/pull/535

**Comment by brianfeucht** [comment]
@spirillen I appreciate your passion for making the internet less shitty.   We are trying our best to help guide the industry in a way that makes it less intrusive and more delightful.  You can send really fun and engaging email that people actually want without doing a bunch of creepy things.  

Thank you!

**Comment by spirillen** [comment]
Hmm, if I get 10 mail in a years, something have gone all wrong... everything is directed to issue boards

Reason: Gmail was hacked, I _almost_ got 2 years in deal, 'cos of falls accusations from my exfg. So nope, I don't do emails any longer ;)
