### ISSUE TITLE
coveo.com

### ISSUE THREAD

**Issue by spirillen** [mypdns/matrix#561]
### Comments

According to @larosek in https://github.com/disconnectme/disconnect-tracking-protection/issues/358 the following domains are used for tracking. However, when I search my third party library I can find a lot more records for this domains.

Maybe you @larosek could help clarify what they are used for?

```
data/UltimateHostsBlacklist1.txt:marketing.coveo.com
data/UltimateHostsBlacklist2.txt:ua2.coveo.com
data/UltimateHostsBlacklist2.txt:usageanalyticsdev.coveo.com
```

### Wildcard domain records

```CSV
analytics.org.coveo.com|tracking
analytics.orghipaa.coveo.com|tracking
analytics.orgdev.coveo.com|tracking
analytics.orgstg.coveo.com|tracking
```

### Sub-Domain records

```CSV
analytics.cloud.coveo.com|tracking
analytics-eu.cloud.coveo.com|tracking
analytics-au.cloud.coveo.com|tracking
analytics-ca.cloud.coveo.com|tracking
analyticshipaa.cloud.coveo.com|tracking
usageanalytics.coveo.com|tracking ; Being deprecated in december 2024
usageanalyticshipaa.coveo.com|tracking ; Being deprecated in december 2024
analyticsdev.cloud.coveo.com|tracking
analyticsdev-eu.cloud.coveo.com|tracking
analyticsstg.cloud.coveo.com|tracking
usageanalyticsdev.coveo.com|tracking ; Being deprecated in december 2024
marketing.coveo.com|tracking
ua2.coveo.com|tracking
```

### Hosts (RFC:953) specific records, not used by DNS RPZ firewalls

```CSV
danaherproductionrfl96bkr.analytics.org.coveo.com
dellprod.analytics.org.coveo.com
intelcorporationproductione78n25s6.analytics.org.coveo.com
intuitproductiono3k66avm.analytics.org.coveo.com
lgcorporationproduction0fxcu0qx.analytics.org.coveo.com
lplfinancialproductioni5zhlpp4.analytics.org.coveo.com
mulesoftprodqzggq6re.analytics.org.coveo.com
nespressoproductiong3iqhhz5.analytics.org.coveo.com
org62salesforce.analytics.org.coveo.com
principalfinancialgroupnonproductionwci0zvut.analytics.org.coveo.com
safecoinsuranceproductionwmvxq3zp.analytics.org.coveo.com
sapamericaproductiontyfzmfz0.analytics.org.coveo.com
smartsheetproductionh5772tp8.analytics.org.coveo.com
societyforhumanresourcemanagementproductionay6r644u.analytics.org.coveo.com
sunbeltrentalsproduction9jbsj6ku.analytics.org.coveo.com
thevanguardgroupproduction7s2cjlnv.analytics.org.coveo.com
thomsonreuterscorporationnonproduction1tuvpj4kh.analytics.org.coveo.com
ultimatesoftware.analytics.org.coveo.com
unitedairlinesproduction5p46fxvr.analytics.org.coveo.com
unitytechnologiesproductionmkahteav.analytics.org.coveo.com
usageanalyticsdev.coveo.com
wolterskluwer6rt6bhff.analytics.org.coveo.com
```

### SeafeSearch records

```CSV
null
```

### Screenshots

![image](https://github.com/mypdns/matrix/assets/44526987/b4a5b606-59a6-49b9-872f-c9f202eb68c7)
It's clear they don't like privacy, AT ALL

### Links to external sources

```CSS
null
```

### logs from uBlock Origin

N/A

**Comment by spirillen** [comment]
Ping @ShadowWhisperer New tracker links you do not have on your list

## Search result from External Hosts-Sources
@mypdns's External Hosts-Sources can be found [here](https://github.com/external-sources/hosts-sources?tab=readme-ov-file#external-sources)

```css
data/QuidsupMixed.txt:usageanalytics.coveo.com
data/ShadowWhispererTracking.txt:analytics.cloud.coveo.com
data/ShadowWhispererTracking.txt:analytics.org.coveo.com
data/ShadowWhispererTracking.txt:usageanalytics.coveo.com
```

**Comment by ShadowWhisperer** [comment]
I have in my notes that blocking these, breaks something. Didn't log specifics.
```
static.cloud.coveo.com
platform.cloud.coveo.com
```

`analytics.org.coveo.com` is in **Wild_Tracking**

Added these to **Tracking**
```
marketing.coveo.com
ua2.coveo.com
```

Thanks!

**Comment by spirillen** [comment]
You can add `platform-eu.cloud.coveo.com` according to info in https://github.com/disconnectme/disconnect-tracking-protection/issues/358

**Comment by jebeaudet** [comment]
Hi,

Pitching in for @larosek here, here is our DNS setup wrt to analytics and functionality. We host a data resident platform so global endpoints are suffixed with a region while organization endpoints (endpoints dedicated to one customer) are global but only point to the proper regions. We also have a HIPAA platform. I've also included our dev/stg endpoints since they are for now public.

We thrive to be transparent in all of this and I'm pretty sure all of the domains are there, I'll reply if some more surface until then.

## Functionality domains
These should not be blocked since they serve the queries, query suggest and other functionalities around search we provide.
### Main endpoint
This is our main multi-tenant endpoints, the endpoints suffixed with 0 and 1 are used to help with concurrent request limits in chrome (these could probably be removed with http2+)
```
platform.cloud.coveo.com
platform0.cloud.coveo.com 
platform1.cloud.coveo.com 
platform-eu.cloud.coveo.com
platform-eu0.cloud.coveo.com
platform-eu1.cloud.coveo.com
platform-au.cloud.coveo.com
platform-au0.cloud.coveo.com
platform-au1.cloud.coveo.com
platform-ca.cloud.coveo.com
platform-ca0.cloud.coveo.com
platform-ca01.cloud.coveo.com
platformhipaa.cloud.coveo.com
platformhipaa0.cloud.coveo.com
platformhipaa1.cloud.coveo.com
cloudplatform.coveo.com #Being deprecated in december 2024
platformdev.cloud.coveo.com
platformdev0.cloud.coveo.com
platformdev1.cloud.coveo.com
platformdev-eu.cloud.coveo.com
platformdev-eu0.cloud.coveo.com
platformdev-eu1.cloud.coveo.com
platformstg.cloud.coveo.com
platformstg0.cloud.coveo.com
platformstg1.cloud.coveo.com
```

### CDN
Our CDN `static.cloud.coveo.com` which host our [search-ui](https://github.com/coveo/search-ui) or the more recent [ui-kit](https://github.com/coveo/ui-kit).
```
static.cloud.coveo.com
staticdev.cloud.coveo.com
staticstg.cloud.coveo.com
```

### Search pages endpoint
These records are used for our hosted search page service : 
```
search.cloud.coveo.com
search-eu.cloud.coveo.com
search-au.cloud.coveo.com
search-ca.cloud.coveo.com
searchhipaa.cloud.coveo.com
searchdev.cloud.coveo.com
searchdev-eu.cloud.coveo.com
searchstg.cloud.coveo.com
```
### Organization endpoints
These single tenant records point to a specific client. Each client has 3 records, one for distributed search, one for administration API and one for analytics. These one should not be blocked (analytics are listed in the other section): 
```
*.org.coveo.com
*.orghipaa.coveo.com
*.admin.org.coveo.com
*.admin.orghipaa.coveo.com
*.orgdev.coveo.com
*.admin.orgdev.coveo.com
*.orgstg.coveo.com
*.admin.orgstg.coveo.com
```

## Analytics domains
These can be safely blocked : 
```
*.analytics.org.coveo.com
*.analytics.orghipaa.coveo.com
analytics.cloud.coveo.com
analytics-eu.cloud.coveo.com
analytics-au.cloud.coveo.com
analytics-ca.cloud.coveo.com
analyticshipaa.cloud.coveo.com
usageanalytics.coveo.com #Being deprecated in december 2024
usageanalyticshipaa.coveo.com #Being deprecated in december 2024
*.analytics.orgdev.coveo.com
*.analytics.orgstg.coveo.com
analyticsdev.cloud.coveo.com
analyticsdev-eu.cloud.coveo.com
analyticsstg.cloud.coveo.com
usageanalyticsdev.coveo.com #Being deprecated in december 2024
```

## Other domains
We have full control on our platform records (the ones listed before this section), however, as we are not a startup anymore, we don't control everything for all the departments. Therefore, domains like `marketing.coveo.com` and `ua2.coveo.com` are out of ouir control but they do seems like something that could be blocked.

**Comment by spirillen** [comment]
Thanks to @jebeaudet & @larosek for helping clarifying which domains are doing the evil stuff and which should be considered ok to access.

**Comment by spirillen** [comment]
PS: DNS records is updated too. Hoping they match :wink:

**Comment by spirillen** [comment]
@Mblanchetdeverly I'm not sure why you mention commit https://github.com/mypdns/matrix/commit/da771ed9400144b922d7264bab3af4dfeba964fc in https://github.com/disconnectme/disconnect-tracking-protection/issues/361 as we do not block `platform.cloud.coveo.com, platform-eu.cloud.coveo.com` as specified in https://github.com/mypdns/matrix/issues/561#issuecomment-2168015706

What you see here, and might have been misreading is a 1 to 1 domain blacklist

https://github.com/mypdns/matrix/commit/da771ed9400144b922d7264bab3af4dfeba964fc#diff-70a539ad5bf201cbd7e02966aed5e5199e557adeb65fdf77fb26af552893c287R503-R509

**Comment by jebeaudet** [comment]
@spirillen that's what https://github.com/disconnectme/disconnect-tracking-protection/issues/361 is saying, this PR is OK since it does _not_ block platform/platform-eu.cloud.coveo.com as opposed to https://github.com/disconnectme/disconnect-tracking-protection/commit/25d7af6aa3f6c530b53800f706952a920e76a623 which does block the 2 domains.

**Comment by spirillen** [comment]
Super... then we are good :+1:
